name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y libatk1.0-dev libpango1.0-dev libgdk-pixbuf-2.0-dev libgtk-4-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
